# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_agency', models.CharField(max_length=50, verbose_name='Funding Agency')),
                ('pi_designation', models.CharField(max_length=50, verbose_name='PI and Designation')),
                ('co_pi_designation', models.CharField(max_length=50, verbose_name='Co-PI and Designation')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('amount_sactioned', models.IntegerField(verbose_name='Amount Sanctioned')),
            ],
        ),
    ]
