# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('OnGoing', 'OnGoing')], default='Completed', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
    ]
