# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170804_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='hello', max_length=300, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='co_pi_designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Co-PI and Designation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_agency',
            field=models.CharField(max_length=100, verbose_name='Funding Agency'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_designation',
            field=models.CharField(max_length=100, verbose_name='PI and Designation'),
        ),
    ]
