# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170808_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_sactioned',
            field=models.CharField(max_length=50, verbose_name='Amount Sanctioned'),
        ),
    ]
