# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170808_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('funding_agency', models.CharField(max_length=100, verbose_name='Funding Agency')),
                ('pi_designation', models.CharField(max_length=100, verbose_name='PI and Designation')),
                ('co_pi_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Co-PI and Designation')),
                ('submission_date', models.DateField(verbose_name='Submission Date')),
                ('amount_applied', models.CharField(max_length=50, verbose_name='Amount Applied')),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='FundedProject',
        ),
    ]
