# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170808_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundedproject',
            name='amount_sactioned',
            field=models.IntegerField(max_length=50, verbose_name='Amount Sanctioned'),
        ),
    ]
