# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20170818_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='amount_applied',
        ),
        migrations.AddField(
            model_name='proposal',
            name='p_amount_applied',
            field=models.IntegerField(default=10, verbose_name='Amount Applied'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundedproject',
            name='amount_sactioned',
            field=models.IntegerField(verbose_name='Amount Sanctioned'),
        ),
    ]
