# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0003_auto_20170712_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('Journal', 'Conformal'), ('red', 'red')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
