# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0004_auto_20170712_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='nationality',
            field=models.CharField(choices=[('national', 'national'), ('international', 'international')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('conformal', 'conformal'), ('Jornal', 'Jornal')], max_length=100),
        ),
    ]
