# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0005_auto_20170712_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='page_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('conformal', 'conformal'), ('Journal', 'Journal')], max_length=100),
        ),
    ]
