# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0006_auto_20170712_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('conference', 'conference'), ('Journal', 'Journal')], max_length=100),
        ),
    ]
