# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0007_auto_20170712_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='page_no',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
