# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0010_auto_20170712_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='page_no',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
    ]
