# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0012_auto_20170712_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citations',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='impact_factor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
