# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0015_auto_20170804_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='Journal_name',
            field=models.CharField(max_length=100, verbose_name='Journal/Conference Name'),
        ),
    ]
