# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phd_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dept', models.CharField(max_length=200)),
                ('guide', models.CharField(max_length=200)),
                ('uni', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('details', models.TextField()),
                ('comprehensive_views', models.TextField()),
                ('related_publications', models.TextField()),
                ('workshops_attended', models.CharField(max_length=200)),
                ('trainings_attended', models.CharField(max_length=200)),
                ('funded_projects', models.CharField(max_length=200)),
                ('other', models.TextField()),
            ],
        ),
    ]
