# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phd_status',
            new_name='phd_statu',
        ),
    ]
