# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0002_auto_20170718_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phd_statu',
            new_name='phd_status',
        ),
    ]
