# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0003_auto_20170718_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_status',
            name='comprehensive_views',
            field=models.TextField(verbose_name='Comprehensive viva voce'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='dept',
            field=models.CharField(max_length=200, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='details',
            field=models.TextField(verbose_name='Details of work'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='funded_projects',
            field=models.CharField(max_length=200, verbose_name='Any funded porposal made  with respected research topic'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='guide',
            field=models.CharField(max_length=200, verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='other',
            field=models.TextField(verbose_name='Any other details'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='related_publications',
            field=models.TextField(verbose_name='publications related to research topic'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='trainings_attended',
            field=models.CharField(max_length=200, verbose_name='Any trainings attended for supporting chosen research topic'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='uni',
            field=models.CharField(max_length=200, verbose_name='University where registered'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='workshops_attended',
            field=models.CharField(max_length=200, verbose_name='workshops/seminar/conference'),
        ),
        migrations.AlterField(
            model_name='phd_status',
            name='year',
            field=models.DateField(verbose_name='year of registration'),
        ),
    ]
