# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0004_auto_20170718_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phd_status',
            options={'verbose_name_plural': 'PHD Statuses'},
        ),
    ]
