# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0006_t_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd_status',
            name='details',
        ),
    ]
