# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0008_auto_20170726_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd_status',
            name='details',
        ),
        migrations.AddField(
            model_name='phd_status',
            name='details',
            field=models.ManyToManyField(to='phdstatus.t_details'),
        ),
    ]
