# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0009_auto_20170727_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_status',
            name='details',
            field=models.ManyToManyField(related_name='_phd_status_details_+', to='phdstatus.t_details'),
        ),
    ]
