# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0010_auto_20170727_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd_status',
            name='details',
        ),
        migrations.AddField(
            model_name='phd_status',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.t_details'),
            preserve_default=False,
        ),
    ]
