# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0015_auto_20170727_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd_status',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, related_name='t_details', to='phdstatus.T_details'),
        ),
    ]
