# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0016_auto_20170727_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phd_status',
            name='details',
        ),
        migrations.AddField(
            model_name='t_details',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.Phd_status'),
        ),
    ]
