# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0017_auto_20170728_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phd_status',
            new_name='PhdStatus',
        ),
        migrations.RenameModel(
            old_name='t_details',
            new_name='TableDetails',
        ),
        migrations.AlterModelOptions(
            name='tabledetails',
            options={'verbose_name_plural': 'Details'},
        ),
    ]
