# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0018_auto_20170728_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'Comprehensive viva voce',
                'verbose_name_plural': 'Comprehensive viva voce',
            },
        ),
        migrations.CreateModel(
            name='FundedProjectsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'Any funded porposal made  with respected research topic',
            },
        ),
        migrations.CreateModel(
            name='PublicationsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'Publications related to research topic',
            },
        ),
        migrations.CreateModel(
            name='TrainingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'Any trainings attended for supporting chosen research topic',
            },
        ),
        migrations.CreateModel(
            name='WorkDetailsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'Work Detail',
            },
        ),
        migrations.CreateModel(
            name='WorkshopsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration(Days)')),
            ],
            options={
                'verbose_name': 'workshops/seminar/conference attended',
            },
        ),
        migrations.RemoveField(
            model_name='tabledetails',
            name='phdstatus',
        ),
        migrations.RemoveField(
            model_name='phdstatus',
            name='comprehensive_views',
        ),
        migrations.RemoveField(
            model_name='phdstatus',
            name='funded_projects',
        ),
        migrations.RemoveField(
            model_name='phdstatus',
            name='related_publications',
        ),
        migrations.RemoveField(
            model_name='phdstatus',
            name='trainings_attended',
        ),
        migrations.RemoveField(
            model_name='phdstatus',
            name='workshops_attended',
        ),
        migrations.DeleteModel(
            name='TableDetails',
        ),
        migrations.AddField(
            model_name='workshopstable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AddField(
            model_name='workdetailstable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AddField(
            model_name='trainingtable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AddField(
            model_name='publicationstable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AddField(
            model_name='fundedprojectstable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AddField(
            model_name='comprehensivetable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
    ]
