# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0019_auto_20170728_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phdstatus',
            options={'verbose_name_plural': 'Ph.D Status'},
        ),
    ]
