# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0020_auto_20170803_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatusTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=50, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Course Work Status',
            },
        ),
        migrations.RemoveField(
            model_name='publicationstable',
            name='phdstatus',
        ),
        migrations.RemoveField(
            model_name='workdetailstable',
            name='phdstatus',
        ),
        migrations.AlterModelOptions(
            name='fundedprojectstable',
            options={'verbose_name': 'Proposals submitted relating to the Research Topic'},
        ),
        migrations.AlterModelOptions(
            name='trainingtable',
            options={'verbose_name': 'Any other trainings'},
        ),
        migrations.AlterModelOptions(
            name='workshopstable',
            options={'verbose_name': 'Workshops/seminar/conference attended'},
        ),
        migrations.RemoveField(
            model_name='comprehensivetable',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='fundedprojectstable',
            name='duration',
        ),
        migrations.AddField(
            model_name='comprehensivetable',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Completed', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundedprojectstable',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Funding Agency'),
        ),
        migrations.AddField(
            model_name='fundedprojectstable',
            name='funding_sought',
            field=models.IntegerField(blank=True, null=True, verbose_name='Funding sought'),
        ),
        migrations.AddField(
            model_name='fundedprojectstable',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Completed', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundedprojectstable',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
        migrations.AddField(
            model_name='phdstatus',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], default='Completed', max_length=50, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdstatus',
            name='synopsys',
            field=models.CharField(choices=[('approved', 'approved'), ('not approved', 'not approved')], default='approved', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtable',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='workshopstable',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='phdstatus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Research Scholar Name'),
        ),
        migrations.DeleteModel(
            name='PublicationsTable',
        ),
        migrations.DeleteModel(
            name='WorkDetailsTable',
        ),
        migrations.AddField(
            model_name='workstatustable',
            name='phdstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
    ]
