# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0021_auto_20170803_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtable',
            options={'verbose_name': 'Any other training'},
        ),
        migrations.AlterModelOptions(
            name='workshopstable',
            options={'verbose_name_plural': 'Workshops/seminar/conference attended'},
        ),
        migrations.AlterModelOptions(
            name='workstatustable',
            options={'verbose_name_plural': 'Course Work Status'},
        ),
        migrations.AlterField(
            model_name='comprehensivetable',
            name='phdstatus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phdstatus.PhdStatus'),
        ),
        migrations.AlterField(
            model_name='comprehensivetable',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='fundedprojectstable',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='phdstatus',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='Any other details'),
        ),
        migrations.AlterField(
            model_name='trainingtable',
            name='details',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='trainingtable',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration(Days)'),
        ),
        migrations.AlterField(
            model_name='trainingtable',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workshopstable',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration(Days)'),
        ),
        migrations.AlterField(
            model_name='workshopstable',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='title'),
        ),
    ]
