# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phdstatus', '0023_auto_20170804_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprehensivetable',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Not Completed', 'Not Completed')], max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='phdstatus',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('OnGoing', 'OnGoing')], max_length=50, verbose_name='status'),
        ),
    ]
